package com.example.debtbook_backend.utils;

public interface BotSteps {


    String SELECT_LANG = "SELECT_LANG";
    String SEND_CONTACT = "SEND_CONTACT";
    String ADD_STORE = "ADD_STORE";
    String LOCATION = "LOCATION";
    String ADD_DEBTOR = "ADD_DEBTOR";
    String ADD_DEBTOR_PHONE = "ADD_DEBTOR_PHONE";
    String SETTINGS_MENU = "SETTINGS_MENU";
    String MAIN_MENU = "MAIN_MENU";
    String SEE_MY_DEBT = "SEE_MY_DEBT";
    String CHANGE_LANG = "CHANGE_LANG";
    String ADD_DEBT = "ADD_DEBT";
    String HELP = "HELP";
    String ENTER_NAME = "ENTER_NAME";
    String START_WORKING = "START_WORKING";
    String ADD_DEBTOR_NAME = "ADD_DEBTOR_NAME";
    String DEBT_MENU = "DEBT_MENU";
    String REDUCE_DEBT = "REDUCE_DEBT";
    String LIST_DEBTORS = "LIST_DEBTORS";
    String START = "START";
    String ADD_DEBT_CONFIRMATION = "ADD_DEBT_CONFIRMATION";
    String REDUCE_DEBT_CONFIRMATION = "REDUCE_DEBT_CONFIRMATION";
    String CHANGE_STORE = "CHANGE_STORE";
    String CHANGE_DEBTOR = "CHANGE_DEBTOR";
    String STORE_NAME = "STORE_NAME";
    String STORE_LOCATION = "STORE_LOCATION";
    String CABINET = "CABINET";
    String OWNER_NAME = "OWNER_NAME";
    String OWNER_PHONE = "OWNER_PHONE";
    String DEBTOR_NAME = "DEBTOR_NAME";
    String DEBTOR_PHONE = "DEBTOR_PHONE";
    String ADMIN_STORE = "ADMIN_STORE";
    String ADMIN_DEBTOR = "ADMIN_DEBTOR";
}
